### ISSUE TITLE
Missing Docs on How to Create Off-site (iFrame) Payment Gateways

### ISSUE THREAD

**Issue by eloyekunle** [drupalcommerce/commerce-docs#212]
I understand that the processes for creating off-site (iFrame) payment gateways bear a lot of similarities to creating off-site (redirect) payment gateways.
However, the docs are entirely missing [documentation on these processes](https://docs.drupalcommerce.org/commerce2/developer-guide/payments/off-site-iframe-gateways) including adding local/remote javascript libraries, handling payments from the iFrames and so on.

**Comment by playmice** [comment]
I'm currently working on a payment gateway that uses iFrames. I'm making some progress, partly by reading through Commerce code, partly by reading Drupal 7 modules.
I'll be happy to work on this aspect of the documentation.

**Comment by mglaman** [comment]
Thanks for offering to tackle!

I'm at MidCamp and can try to provide any guidance if you need! I'll be in Drupal Slack or here.

The D7 examples should help. I think you may need to override a form? Or something to prevent redirect so you can render the iframe.

The trick is what brings you the value. Popping via iframe. I've done an iframe gateway in D8, but via a custom checkout flow and not the gateway pane (pre-that time.)

**Comment by playmice** [comment]
Now, is it still recommended to create custom checkout flows for iframe gateways?

**Comment by mglaman** [comment]
Nope! @playmice I only did because of other requirements, and it helped spec out our API implementation :)

**Comment by mglaman** [comment]
@playmice I can follow up here or the D.o issue with details once I review our API, again. Have to give a session.

**Comment by playmice** [comment]
Okay, great. I'm making progress with the module I'm building. As you suggested, the main idea was getting the value out of the iFrame.
For example, the payment gateway I'm using currently accept a _Redirect URL_ as a parameter, which is where they send the post values upon payment success/failure/cancellation.
From there, I can take action such as verifying Payment, saving Payment Method for user etc.

So, it's really similar to off-site (redirect) payment except that here, there's no need to build a redirect form. The _Submit_ button has to be overriden so it shows the iFrame instead of triggering a page reload or redirecting to another page.

**Comment by playmice** [comment]
I made a [video demonstration](https://youtu.be/ve7UvEc0xe4) of the iFrame payment gateway.
It's still work in progress but I deployed it on commerce_demo [here](http://shop.elijahoyekunle.com).

**Comment by Shorpee23** [comment]
😮😓

**Comment by lisastreeter** [comment]
Documentation for off-site (iframe) payment gateways has been added.
