### ISSUE TITLE
Product Attributes Feedback Placeholder Issue

### ISSUE THREAD

**Issue by joshmiller83** [drupalcommerce/commerce-docs#30]

**Comment by joshmiller83** [comment]
Regarding PR #19

**Comment by thejacer87** [comment]
- Rewording Needed: "_Finally, users are able select attributes on the product variation type form, the checkbox in the last step automatically created entity referenced fields as needed:_" -- not too sure what to change it to, but i know it doesnt make sense to me. maybe im just reading it with the wrong inflection

- Missing word(s):"_The fieldable attribute value lets the information architect decide what kind of_ **{missing a word here???}** _best describes this attribute (does it need an image field and three text fields? Good, because we can do that)_"

- **Adding fields to Attributes** and **Editing Attributes** sections, show the exact same pics... no differences... is that intentional? should there be something indicating where to look on these?

**Comment by joshmiller83** [comment]
- [ ] doesn't look like the screenshot of the attribute listing is actually needed? Doesn't communicate anything?
- [ ] "The first step in adding an attribute to a product, is to create the type of attribute. For our Drupalcon t-shirt example we are working with two different kinds of attributes: color and size. An attribute can be anything that makes one specific version of a product different from another specific version." -> this feels a bit redundant. Why not jump straight in and say "For our t-shirt we need two attributes: color and size. Let's start by creating the color attribute. Go to admin/commerce/product-attributes and click the Add attribute link."

**Comment by mchuam** [comment]
- [ ] The product attribute values user interface allows creating and re-ordering multiple values at the same time and **a very powerful translation capability**:

I think you might be missing the word "has" - ie. ...same time and HAS a very powerful translation capability.
